server:
  host: 0.0.0.0
  port: 3000
swagger:
  title: NWT_Abli-Bouyo_De_Nonencourt
  description: Description de l'API back-end du projet
  version: 1.0
  tag: back
  path: api
mongodb:
  uri: mongodb://0.0.0.0:27017/nwt
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
